apiVersion: v1
kind: Service
metadata:
  name: real-estate-api
  namespace: default
spec:
  selector:
    app: reo-api # This now correctly matches the Deployment's pod label
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
