apiVersion: v1
kind: Service
metadata:
  name: reo-api-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: reo-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
